#!/bin/bash -x 

cd `dirname $0`/..

echo 'Hola'
 
JAVA_OPTS="$JAVA_OPTS -Xms1G -Xmx=3G -Denvironment=prod"

JAVA_ARGS="$JAVA_ARGS hello"

COMMAND="java $JAVA_OPTS -jar libs/my-project.jar $JAVA_ARGS"

exec -a "my-project" $COMMAND